/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Modelo.Administrador;
import static Vistas.Registrar.listadmin;
import static java.awt.image.ImageObserver.HEIGHT;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Jeremy
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form log
     */
    
    Administrador admin;
    Registrar Ra;



    public login(Administrador admin) {
        initComponents();
        jLabel1.setIcon(new ImageIcon(new ImageIcon("assets/images/system/login.png").getImage().getScaledInstance(560, 381, java.awt.Image.SCALE_DEFAULT)));
        
        setSize(558, 380);
        this.setLocationRelativeTo(null);
        this.admin=admin;
    }

    /*public login(Administrador admin) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }*/

    private login() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }


   
    
    //metodo para iniciar sesion
    public void iniciaSesion() throws Exception{
    
        String aux = "";
        int auxiliar =0;
        
        //obtiene los datos ingresados
        String cor = Ccorreo.getText();
        char passArray[] = Cclave.getPassword();
        
        //Decifra la clave escrita
        for (int i = 0; i < passArray.length; i++) {
            char c = passArray[i];
            
        }
        
        // Convertir la clave a String
        String pass = new String(passArray);
        
       //Validacion de inicio seccion
        if(aux.equals(cor) && passArray.equals(aux)){
            JOptionPane.showMessageDialog(null, "Ingrese correo y contraseña", "Datos incorrecto", HEIGHT);
        }else{ 
            
            //busca los administradores
            for(int i=0;i<listadmin.size();i++){
            admin = (Administrador) listadmin.get(i);
                if(cor.equals(admin.getCorreo()) && !cor.equals(aux) && pass.equals(admin.getContraseña()) && !pass.equals(aux)){
            
                    
                    Chat sc = new Chat(admin.getNombre());
                    
         
                    this.setVisible(false);

                    auxiliar = i;
                   
                    //JOptionPane.showMessageDialog(null, "Se consiguio correctamente", "Datos validado", HEIGHT);

                    break;
                } 
            }
         }
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        Biniciarseccion = new javax.swing.JButton();
        Cclave = new javax.swing.JPasswordField();
        Ccorreo = new javax.swing.JTextField();
        Bregistrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(255, 0, 51));
        jButton1.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("SALIR");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 26, 70, 30));

        Biniciarseccion.setBackground(new java.awt.Color(204, 204, 255));
        Biniciarseccion.setFont(new java.awt.Font("Microsoft Tai Le", 0, 12)); // NOI18N
        Biniciarseccion.setText("INICIAR SESION");
        Biniciarseccion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Biniciarseccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BiniciarseccionActionPerformed(evt);
            }
        });
        getContentPane().add(Biniciarseccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 243, -1, 30));

        Cclave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CclaveActionPerformed(evt);
            }
        });
        getContentPane().add(Cclave, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 230, -1));
        getContentPane().add(Ccorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 230, -1));

        Bregistrar.setBackground(new java.awt.Color(204, 204, 255));
        Bregistrar.setFont(new java.awt.Font("Microsoft Tai Le", 0, 12)); // NOI18N
        Bregistrar.setText("REGISTRARSE");
        Bregistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Bregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BregistrarActionPerformed(evt);
            }
        });
        getContentPane().add(Bregistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 323, -1, 30));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BiniciarseccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BiniciarseccionActionPerformed
        
        try {
            // TODO add your handling code here:
            iniciaSesion();
           
        } catch (Exception ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BiniciarseccionActionPerformed

    private void BregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BregistrarActionPerformed

        Ra = new Registrar();
        Ra.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_BregistrarActionPerformed

    private void CclaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CclaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CclaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Biniciarseccion;
    private javax.swing.JButton Bregistrar;
    private javax.swing.JPasswordField Cclave;
    private javax.swing.JTextField Ccorreo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
